if(${BOARD_INGENIC_T31})
    set(BOARD "T31")
elseif(${BOARD_RPI})
    set(BOARD "V4L2")
elseif(DEFINED ZEPHYR_BASE)
    if(${CONFIG_AWS_MI_BOARD} STREQUAL "STATICIMAGE")
        set(BOARD "STATICIMAGE")
    elseif(${CONFIG_AWS_MI_BOARD} STREQUAL "ANIMATION")
        include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../../src/image/include)
        set(BOARD "ANIMATION")
    elseif(${CONFIG_AWS_MI_BOARD} STREQUAL "LIVESTREAM")
        set(BOARD "LIVESTREAM")
    else()
        message(FATAL_ERROR "Board ${CONFIG_AWS_MI_BOARD} is not defined. Defaulting to FILE despite Zephyr existing.")
        set(BOARD "FILE")
    endif()
else()
    set(BOARD "FILE")
endif()


# get_cmake_property(_variableNames VARIABLES)
# list (SORT _variableNames)
# foreach (_variableName ${_variableNames})
#     message(STATUS "${_variableName}=${${_variableName}}")
# endforeach()

set(BUILD_WEBRTC_SAMPLES_SAVED "${BUILD_WEBRTC_SAMPLES}")
set(BUILD_WEBRTC_SAMPLES OFF)
add_subdirectory(libraries/amazon/amazon-kinesis-video-streams-media-interface)
set(BUILD_WEBRTC_SAMPLES "${BUILD_WEBRTC_SAMPLES_SAVED}")
